#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  OS::TripleO::Controller::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/ceph-storage.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 192.168.100.0/24
  TenantNetCidr: 192.168.103.0/24
  StorageNetCidr: 192.168.101.0/24
  StorageMgmtNetCidr: 192.168.102.0/24
  ExternalNetCidr: 192.168.104.0/24
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '192.168.100.10', 'end': '192.168.100.250'}]
  TenantAllocationPools: [{'start': '192.168.103.10', 'end': '192.168.103.250'}]
  StorageAllocationPools: [{'start': '192.168.101.10', 'end': '192.168.101.250'}]
  StorageMgmtAllocationPools: [{'start': '192.168.102.10', 'end': '192.168.102.250'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '192.168.104.40', 'end': '192.168.104.80'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 192.168.104.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.1.1
  # Generally the IP of the Undercloud
  EC2MetadataIp: 192.168.1.5
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["192.168.104.1"]
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 900
  TenantNetworkVlanID: 903
  StorageNetworkVlanID: 901
  StorageMgmtNetworkVlanID: 902
  #ExternalNetworkVlanID: 904
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "bond_mode=balance-slb"
